name: belatuk_html_builder
version: 4.0.0
description: Build HTML AST's and render them to HTML. This can be used as an internal DSL, i.e. for a templating engine.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/html_builder
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  collection: ^1.15.0
dev_dependencies:
  html: ^0.15.0
  test: ^1.17.4
  lints: ^2.0.0
