name: belatuk_pretty_logging
version: 4.0.0
description: Standalone helper for colorful logging output, using pkg:io AnsiCode.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/pretty_logging
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  io: ^1.0.0
  logging: ^1.0.1
dev_dependencies:
  lints: ^1.0.0
