name: belatuk_common_utilities

packages:
  - packages/body_parser
  - packages/code_buffer
  - packages/combinator
  - packages/html_builder
  - packages/json_serializer
  - packages/merge_map
  - packages/pretty_logging
  - packages/pub_sub
  - packages/range_header
  - packages/symbol_table
  - packages/user_agent

