name: belatuk_common_utilities_workspace

publish_to: none
environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - packages/body_parser
  - packages/code_buffer
  - packages/combinator
  - packages/html_builder
  - packages/json_serializer
  - packages/merge_map
  - packages/pretty_logging
  - packages/pub_sub
  - packages/range_header
  - packages/symbol_table
  - packages/user_agent

dependencies:
  melos: ^7.3.0

melos: