name: belatuk_code_buffer
version: 5.1.0
description: An advanced StringBuffer geared toward generating code, and source maps.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/code_buffer
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  charcode: ^1.2.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
