name: belatuk_json_serializer
version: 7.3.0
description: Easy JSON to Object serialization and deserialization in Dart.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/json_serializer
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  logging: ^1.0.1
dev_dependencies:
  stack_trace: ^1.10.0
  test: ^1.24.0
  lints: ^5.0.0