name: user_agent_analyzer
version: 5.5.0
description: A library to identify the type of devices and web browsers based on User-Agent string.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/user_agent
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
