name: user_agent_analyzer
version: 5.0.0-beta.1
description: A library to identify the type of devices and web browsers based on User-Agent string.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/user_agent
environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'
dev_dependencies:
  test: ^1.17.8
  lints: ^2.0.0
