name: user_agent_analyzer
version: 3.1.0
description: A library to identify the type of devices and web browsers based on User-Agent string.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/user_agent
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.17.8
  lints: ^1.0.0
