name: belatuk_symbol_table
version: 5.5.0
description: A generic symbol table implementation in Dart, with support for scopes and constants.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/symbol_table
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  collection: ^1.17.0  

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
