name: belatuk_body_parser
version: 5.3.0
description: Parse request bodies and query strings in Dart. Supports JSON, URL-encoded, and multi-part bodies.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/body_parser
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  http_parser: ^4.0.0
  belatuk_http_server: ^4.4.0
  mime: ^1.0.0
dev_dependencies:
  http: ^1.0.0
  test: ^1.24.0
  lints: ^5.0.0