name: belatuk_body_parser
version: 3.0.1
description: Parse request bodies and query strings in Dart. Supports JSON, URL-encoded, and multi-part bodies.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/body_parser
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http_parser: ^4.0.0
  belatuk_http_server: ^2.0.0
  mime: ^1.0.0
dev_dependencies:
  http: ^0.13.0
  test: ^1.17.8
  lints: ^1.0.0