name: belatuk_pub_sub
version: 6.0.0-beta.1
description: Keep application instances in sync with a simple pub/sub API.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/pub_sub
environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'
dependencies:
  json_rpc_2: ^3.0.0
  stream_channel: ^2.1.0
  uuid: ^3.0.4
  collection: ^1.15.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.4
