name: belatuk_pub_sub
version: 6.4.0
description: Keep application instances in sync with a simple pub/sub API.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/pub_sub
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  json_rpc_2: ^3.0.0
  stream_channel: ^2.1.0
  uuid: ^4.0.0
  collection: ^1.17.0
dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
