name: belatuk_merge_map
version: 3.0.2
description: Combine multiple Maps into one. Equivalent to Object.assign in JS.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/merge_map
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.17.4
  lints: ^1.0.0
