name: belatuk_range_header
version: 6.0.0-beta.1
description: Range header parser for Dart. Beyond parsing, a stream transformer is included.
homepage: https://github.com/dart-backend/belatuk-common-utilities/tree/main/packages/range_header
environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'
dependencies:
  async: ^2.6.0
  charcode: ^1.2.0
  quiver: ^3.0.1
  source_span: ^1.8.1
  string_scanner: ^1.1.0
dev_dependencies:
  file: ^6.1.0
  http_parser: ^4.0.0
  logging: ^1.0.1
  test: ^1.17.8
  lints: ^2.0.0
